#!/bin/bash
DMENU='dmenu -i'
choice=$(echo -e "suspend\nhibernate\nreboot\nshutdown" | $DMENU)
case "$choice" in
  shutdown)  sudo shutdown -h now & ;;
  reboot)    sudo shutdown -r now & ;;
  suspend)   sudo pm-suspend & ;;
  hibernate) sudo pm-hibernate & ;;
esac
