#! /bin/sh
#
# Example panel for LemonBoy's bar

. panel_colors

num_mon=$(bspc query -M | wc -l)

while read -r line ; do
    case $line in
        S*)
            # clock output
            sys_infos="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG} ${line#?} %{B-}%{F-}"
            ;;
        W*)
            # bspwm internal state
            wm_infos=""
            FG=$COLOR_FOREGROUND
            BG=$COLOR_BACKGROUND
            IFS=':'
            set -- ${line#?}
            while [ $# -gt 0 ] ; do
                item=$1
                name=${item#?}
                padding=""
                action=""
                case $item in
                    M*)
                        # active monitor
                        if [ $num_mon -gt 1 ] ; then
                            BG=$COLOR_ACTIVE_MONITOR_BG
                            FG=$COLOR_ACTIVE_MONITOR_FG
                            padding=' '
                        fi
                        ;;
                    m*)
                        # inactive monitor
                        if [ $num_mon -gt 1 ] ; then
                            BG=$COLOR_INACTIVE_MONITOR_BG
                            FG=$COLOR_INACTIVE_MONITOR_FG
                            padding=' '
                        fi
                        ;;
                    O*)
                        # focused occupied desktop
                        BG=$COLOR_FOCUSED_OCCUPIED_BG
                        FG=$COLOR_FOCUSED_OCCUPIED_FG
                        action="bspc desktop -f ${name}"
                        ;;
                    F*)
                        # focused free desktop
                        BG=$COLOR_FOCUSED_FREE_BG
                        FG=$COLOR_FOCUSED_FREE_FG
                        action="bspc desktop -f ${name}"
                        ;;
                    U*)
                        # focused urgent desktop
                        BG=$COLOR_FOCUSED_URGENT_BG
                        FG=$COLOR_FOCUSED_URGENT_FG
                        action="bspc desktop -f ${name}"
                        ;;
                    o*)
                        # occupied desktop
                        BG=$COLOR_OCCUPIED_BG
                        FG=$COLOR_OCCUPIED_FG
                        action="bspc desktop -f ${name}"
                        ;;
                    f*)
                        # free desktop
                        BG=$COLOR_FREE_BG
                        FG=$COLOR_FREE_FG
                        action="bspc desktop -f ${name}"
                        ;;
                    u*)
                        # urgent desktop
                        BG=$COLOR_URGENT_BG
                        FG=$COLOR_URGENT_FG
                        action="bspc desktop -f ${name}"
                        ;;
                    L*)
                        # layout
                        FG=$COLOR_LAYOUT_FG
                        BG=$COLOR_LAYOUT_BG
                        action="bspc desktop -l next"
                        padding=' '
                        ;;
                esac
                wm_infos="$wm_infos$padding%{F$FG}%{B$BG}%{A:$action:} ${name} %{A}%{B-}%{F-}$padding"
                shift
            done
            ;;
    esac
    printf "%s\n" "%{l}%{A:rofi -fuzzy -sidebar-mode -show run:} Applications %{A}${wm_infos}${title}%{r}${sys_infos}"
done
