#! /bin/sh
bspc config border_width 1
bspc config window_gap 8
bspc config top_padding 16
bspc config bottom_padding 0
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_by_distance true
bspc config focus_follows_pointer true

bspc monitor -d I II III IV V VI VII VIII IX

bspc desktop I -l monocle

bspc rule -a Gimp desktop=^VIII follow=on floating=on

xcompmgr &
feh --bg-scale $HOME/.wallpapers/Arch-Gradient.png &
sxhkd &
export PANEL_FIFO=/tmp/panel-fifo
export PATH=$PATH:$HOME/.config/bspwm/panel
export PANEL_FONT_FAMILY='-*-terminus-medium-r-normal-*-12-*-*-*-c-*-*-1'
export PANEL_HEIGHT=15
$HOME/.config/bspwm/panel/panel &
