#! /bin/sh

sxhkd &
xcompmgr &

bspc config border_width 1
bspc config window_gap 8
bspc config top_padding 0
bspc config bottom_padding 20

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor -d I II III IV V VI VII VIII IX

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a volwheel floating=on

feh --bg-scale ~/linuxdotfiles/.wallpapers/Arch-Gradient.png

# TODO: Replace with dzen2?
tint2 &
nm-applet &
